name: EX Emulators

on: 
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ["Snes9x", "Snes9x-1.43-9", "Snes9x-1.43-15"]

    steps:
    - name: Checkout emu-ex-plus-alpha repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Decode debug keystore
      env:
        DEBUG_KEYSTORE: ${{ secrets.DEBUG_KEYSTORE }}
      run: |
        if [ -z "$DEBUG_KEYSTORE" ]
        then
          echo "No debug keystore value"
        else
          echo $DEBUG_KEYSTORE > debug.keystore.base64
          base64 --decode debug.keystore.base64 > debug.keystore
          sudo mkdir -p /root/.android
          sudo cp -f debug.keystore /root/.android/.
        fi

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends autoconf automake autopoint bash binutils-arm-linux-gnueabi clang cmake file gawk gettext git libtool libtool-bin llvm make nasm pkg-config unzip wget

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Set up environment
      run: |
        mkdir imagine-sdk
        mkdir EX-Emulators
        wget "https://dl.google.com/android/repository/android-ndk-r27-beta2-linux.zip"
        unzip android-ndk-r27-beta2-linux.zip
        echo "ANDROID_NDK_PATH=${{ github.workspace }}/android-ndk-r27-beta2" >> $GITHUB_ENV
        echo "EMUFRAMEWORK_PATH=${{ github.workspace }}/EmuFramework" >> $GITHUB_ENV
        echo "IMAGINE_PATH=${{ github.workspace }}/imagine" >> $GITHUB_ENV
        echo "IMAGINE_SDK_PATH=${{ github.workspace }}/imagine-sdk" >> $GITHUB_ENV
        echo "COMMIT_PREFIX=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_ENV

    - name: Run script
      run: |
        cd imagine/bundle/all
        chmod +x ./makeAll-android.sh
        ./makeAll-android.sh install
      shell: bash

    - name: Build environment
      run: |
        make -f $IMAGINE_PATH/android-release.mk install V=1 -j`nproc`
        make -f $EMUFRAMEWORK_PATH/android-release.mk config -j`nproc`
        make -f $EMUFRAMEWORK_PATH/android-release.mk install V=1 -j`nproc`

    - name: Build Snes9x
      if: ${{ matrix.image == 'Snes9x' }}
      run: |
        cd Snes9x
        make -f android-release.mk android-apk V=1 -j`nproc`
        cp target/android-release/build/outputs/apk/release/Snes9xEXPlus-release.apk "../EX-Emulators/Snes9xEXPlus-${COMMIT_PREFIX}.apk"

    - name: Build Snes9x-1.43-9
      if: ${{ matrix.image == 'Snes9x-1.43-9' }}
      run: |
        cd Snes9x/1.43
        make -f android-release-9.mk android-apk V=1 -j`nproc`
        cp target/android-release-9/build/outputs/apk/release/Snes9xEX-release.apk "../../EX-Emulators/Snes9xEX-9-${COMMIT_PREFIX}.apk"

    - name: Build Snes9x-1.43-15
      if: ${{ matrix.image == 'Snes9x-1.43-15' }}
      run: |
        cd Snes9x/1.43
        make -f android-release-15.mk android-apk V=1 -j`nproc`
        cp target/android-release-15/build/outputs/apk/release/Snes9xEX-release.apk "../../EX-Emulators/Snes9xEX-15-${COMMIT_PREFIX}.apk"

    - name: Upload EX-Emulators artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.image }}
        path: EX-Emulators/
