name: EX Emulators

on: 
  workflow_dispatch:

jobs:
  build:
    name: Build Snes9x EX Plus
    runs-on: ubuntu-latest

    steps:
    - name: Checkout emu-ex-plus-alpha repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Cache Android NDK
      uses: actions/cache@v4
      with:
        path: android-ndk-r27-beta2
        key: android-ndk-r27-beta2

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

    - name: Cache Imagine SDK
      uses: actions/cache@v4
      with:
        path: imagine-sdk
        key: imagine-sdk-${{ hashFiles('imagine/**') }}

    - name: Install build dependencies (ARM64 optimized)
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          autoconf automake autopoint bash clang cmake \
          file gawk gettext git libtool libtool-bin \
          llvm make pkg-config unzip wget

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Set up Gradle optimization
      run: |
        mkdir -p ~/.gradle
        echo "org.gradle.daemon=true" >> ~/.gradle/gradle.properties
        echo "org.gradle.parallel=true" >> ~/.gradle/gradle.properties
        echo "org.gradle.configureondemand=true" >> ~/.gradle/gradle.properties

    - name: Set up environment
      run: |
        mkdir -p imagine-sdk
        mkdir -p EX-Emulators
        if [ ! -f android-ndk-r27-beta2/ndk-build ]; then
          wget "https://dl.google.com/android/repository/android-ndk-r27-beta2-linux.zip"
          unzip android-ndk-r27-beta2-linux.zip
        fi
        echo "ANDROID_NDK_PATH=${{ github.workspace }}/android-ndk-r27-beta2" >> $GITHUB_ENV
        echo "EMUFRAMEWORK_PATH=${{ github.workspace }}/EmuFramework" >> $GITHUB_ENV
        echo "IMAGINE_PATH=${{ github.workspace }}/imagine" >> $GITHUB_ENV
        echo "IMAGINE_SDK_PATH=${{ github.workspace }}/imagine-sdk" >> $GITHUB_ENV
        echo "COMMIT_PREFIX=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_ENV
        echo "android_arch=arm64" >> $GITHUB_ENV

    - name: Run script
      run: |
        cd imagine/bundle/all
        chmod +x ./makeAll-android-arm64.sh
        ./makeAll-android-arm64.sh install
      shell: bash

    - name: Build environment
      run: |
        make -f $IMAGINE_PATH/android-release.mk install V=1 -j`nproc` android_arch=arm64
        make -f $EMUFRAMEWORK_PATH/android-release.mk config -j`nproc` android_arch=arm64
        make -f $EMUFRAMEWORK_PATH/android-release.mk install V=1 -j`nproc` android_arch=arm64

    - name: Build Snes9x (ARM64 only)
      run: |
        cd Snes9x
        make -f android-release.mk android-apk V=1 -j`nproc` android_arch=arm64
        cp target/android-release/build/outputs/apk/release/Snes9xEXPlus-release.apk "../EX-Emulators/Snes9xEXPlus-${COMMIT_PREFIX}.apk"

    - name: Upload Snes9x EX Plus artifact
      uses: actions/upload-artifact@v4
      with:
        name: Snes9xEXPlus
        path: EX-Emulators/
